In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('../DataSets/Abalone.csv',header=None)
df

      0      1      2      3       4       5       6       7   8
0     M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.1500  15
1     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
2     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
3     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
4     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4172  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4173  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4174  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4175  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4176  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4177 rows x 9 columns]

In [3]:
columns=['Sex','Length','Diameter','Height','Whole_Height',
        'Shucked_Weight','Viscera_Weight','Shell_Weight','Rings']

In [4]:
df.columns=columns

In [5]:
df.head()

,Sex,Length,Diameter,Height,Whole_Height,Shucked_Weight,Viscera_Weight,Shell_Weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [6]:
def change(x):
    return x+1.5

In [7]:
change(2)

3.5

In [8]:
df['Age'] = df.Rings.apply(lambda x : x + 1.5)

In [9]:
df

,Sex,Length,Diameter,Height,Whole_Height,Shucked_Weight,Viscera_Weight,Shell_Weight,Rings,Age
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,16.5
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,8.5
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,10.5
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,11.5
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,8.5
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,12.5
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,11.5
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,10.5
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,11.5
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,13.5

In [10]:
df.dtypes

Sex                object
Length            float64
Diameter          float64
Height            float64
Whole_Height      float64
Shucked_Weight    float64
Viscera_Weight    float64
Shell_Weight      float64
Rings               int64
Age               float64
dtype: object

In [11]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_Height      0
Shucked_Weight    0
Viscera_Weight    0
Shell_Weight      0
Rings             0
Age               0
dtype: int64

In [12]:
df.corr(numeric_only=True)

,Length,Diameter,Height,Whole_Height,Shucked_Weight,Viscera_Weight,Shell_Weight,Rings,Age
Length,1.000000,0.986812,0.827554,0.925261,0.897914,0.903018,0.897706,0.556720,0.556720
Diameter,0.986812,1.000000,0.833684,0.925452,0.893162,0.899724,0.905330,0.574660,0.574660
Height,0.827554,0.833684,1.000000,0.819221,0.774972,0.798319,0.817338,0.557467,0.557467
Whole_Height,0.925261,0.925452,0.819221,1.000000,0.969405,0.966375,0.955355,0.540390,0.540390
Shucked_Weight,0.897914,0.893162,0.774972,0.969405,1.000000,0.931961,0.882617,0.420884,0.420884
Viscera_Weight,0.903018,0.899724,0.798319,0.966375,0.931961,1.000000,0.907656,0.503819,0.503819
Shell_Weight,0.897706,0.905330,0.817338,0.955355,0.882617,0.907656,1.000000,0.627574,0.627574
Rings,0.556720,0.574660,0.557467,0.540390,0.420884,0.503819,0.627574,1.000000,1.000000
Age,0.556720,0.574660,0.557467,0.540390,0.420884,0.503819,0.627574,1.000000,1.000000

In [13]:
dt = pd.get_dummies(data=df,columns=['Sex'],drop_first=True)
dt

,Length,Diameter,Height,Whole_Height,Shucked_Weight,Viscera_Weight,Shell_Weight,Rings,Age,Sex_I,Sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,16.5,0,1
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,8.5,0,1
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,10.5,0,0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,11.5,0,1
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,8.5,1,0
...,...,...,...,...,...,...,...,...,...,...,...
4172,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,12.5,0,0
4173,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,11.5,0,1
4174,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,10.5,0,1
4175,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,11.5,0,0
4176,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,13.5,0,1

In [28]:
x=dt.drop(['Age'],axis=1)

In [29]:
y=dt['Age']

In [30]:
from sklearn.model_selection import train_test_split
xtr,xtes,ytr,ytes=train_test_split(x,y,test_size=0.2)

In [45]:
from sklearn.svm import SVR
model=SVR(C=30)
model.fit(xtr,ytr)

SVR(C=30)

In [46]:
ypr=model.predict(xtes)
ypr

array([ 8.52190246, 19.46809178, 12.51807898, 10.52479526, 11.51819562,
        9.5682803 , 15.53852375,  8.4966061 ,  3.61334358, 16.5492946 ,
       12.51605268, 11.51400707, 11.53965453, 12.51651739, 12.52047224,
       12.5372109 , 13.52669318,  8.50440272,  4.56751481, 12.50409536,
       12.50494449,  9.55461773,  9.50763259,  9.52771444, 17.54582686,
       11.5367647 , 10.51915469, 23.46440262,  8.50512311,  8.50263867,
       12.52953589, 13.55844637, 12.50334815,  7.48009539, 10.51768724,
        8.51066654,  9.54311997, 16.54810531, 12.51673404,  9.51214998,
       18.52758572, 12.52183007, 15.54164115, 13.53078361, 11.53058725,
        9.52081836, 11.5012535 , 13.52254784,  9.51944818,  8.50440009,
       14.56631901, 11.50003017,  9.5096953 , 13.52180697, 13.51701572,
       12.51607835, 11.5786356 , 12.51087643, 11.50222604,  9.54994279,
        8.51207389, 13.51217562,  8.52767867, 18.51771896, 17.53836501,
       11.52545878, 11.50678483, 11.51946216,  8.5184044 ,  8.49862462,
        9.55250133, 11.52137997, 10.53952405, 21.40078465, 12.59344304,
        8.51346316, 11.53420856, 11.53845537,  9.52186219, 13.5158013 ,
       11.51205616, 10.51749491,  7.48457945,  9.51661509,  8.51456266,
       10.52195671,  9.53193051,  9.52163693, 14.53736708, 12.53029114,
       14.54287113, 11.5812624 , 11.51519581, 11.53838413, 11.55274078,
        8.51263134, 10.5718506 , 11.507947  , 15.55110507,  7.47468383,
        9.51274266,  6.4242928 , 14.54545404, 13.52136765, 12.51924008,
       10.52569374, 10.51651219, 17.55905759, 18.51688911, 11.51514197,
       13.5301582 , 11.51674687,  7.50360512, 14.56749339, 18.53166634,
       18.52567153, 19.4926656 , 11.54134493, 19.49028485, 10.57671864,
       13.50681643, 12.55656085,  9.55797864, 13.52590813, 16.5571951 ,
       12.51641   , 11.51623088,  9.52539247,  8.51078444, 16.55694834,
       10.53440484, 10.51876427, 11.51601875, 13.52719485,  7.46798003,
       10.52273176,  9.54305205, 12.50428423, 12.51687015,  7.45993713,
       11.50055898, 13.55340661,  8.5245723 , 12.54447858, 12.54494121,
       12.51837814,  8.51269479, 12.50019672, 10.50628487, 14.53104326,
        6.41835031, 16.55954487,  8.49675868, 17.54949904, 13.51475754,
        8.51901717,  8.51462048,  9.5218588 , 11.51787037,  7.46495434,
       10.51790646, 10.54070903, 15.54784889,  9.53298875,  9.53098579,
       10.5597247 ,  6.42822895, 15.53072469, 13.56318335, 15.53121633,
       17.54694405,  9.54655148, 12.51382518, 14.56197248,  9.50705107,
       10.51353766, 10.50220717, 11.59081174, 10.53776937,  9.50901634,
       11.56612793, 12.56835767,  8.4995637 ,  9.53433842, 14.54626859,
        9.50942862,  9.51837948,  8.50907425, 19.49635883,  8.50311182,
       11.57507656, 21.42180431, 10.56053447, 10.51134385, 12.53069574,
        5.40310938, 10.51960483, 13.53927208,  9.53679982, 10.55062669,
       13.50701668, 11.51433435, 16.55778841, 11.51127726, 11.49897484,
       11.50754357,  8.50327094,  6.42080006,  9.52729909, 10.52327577,
       10.51729227, 10.56152686,  9.5325012 ,  8.53858972, 16.55123688,
        9.55303105, 12.5062558 ,  8.52389696, 13.52602229, 16.56035749,
       11.52771424,  6.4273408 ,  7.4838432 ,  7.47852903, 11.5046003 ,
       13.53719456, 10.51513121, 11.50565558,  7.4866443 , 13.53644194,
        9.51215723, 11.51916241,  9.52468401,  7.48140214,  7.4856078 ,
       13.52130047,  9.53553195, 13.55030137, 11.52028695, 10.50518304,
       12.49934347, 10.52702009,  9.50909482, 14.5131927 , 10.5078389 ,
       10.53574514, 14.5406163 ,  8.51383083,  5.40338631,  9.54088079,
        8.51568986, 12.52781119, 11.52978713,  8.49555109,  7.47951431,
       24.49962329, 11.54762613, 21.42898781, 12.52577271, 13.5246898 ,
        4.44724567,  6.42437031,  9.51143583, 10.57242971, 11.51770582,
        6.42905659,  9.51315531, 11.50149767, 10.50508923, 13.55196275,
        4.44813948, 11.51046919, 10.51341166, 12.56017454, 15.57434605,
       11.50222718, 10.56262778,  6.42924471, 11.51384735, 13.52253056,
       10.54213246,  9.50655672,  9.56868144,  6.43112607, 11.54558106,
       20.44771985,  9.55596315, 11.51326394, 11.50588634, 12.51527375,
       10.52426793, 11.53606837, 10.51806653, 10.5700433 , 12.52598592,
        5.40434756,  9.55435228, 10.52846516,  7.4720217 ,  8.50234906,
       10.52107915, 14.57376104, 13.53188753, 12.59353066, 12.52094271,
       17.54242874, 11.50658825, 22.4188765 ,  9.54758305,  6.43200886,
       19.48420149,  8.51077796, 12.54083699,  9.5405601 , 13.51047183,
       13.52994984, 12.51712374, 17.53507825,  7.47237415, 10.54156032,
       11.51663964, 10.50505014, 11.52300184,  9.5488393 , 11.51856637,
       10.50976308,  9.53814609, 12.49939393, 11.52644911, 14.54346358,
       11.56998646, 10.50762426,  6.41149361,  7.47433944, 11.54510865,
        8.51894041, 11.52232185, 13.53815778, 15.54324493,  6.43006634,
       10.5224234 , 12.53050239, 10.53590536, 11.50617482, 13.52540964,
        8.51649933,  8.53884671,  9.53075426, 17.54914214, 10.51827482,
       13.51520266, 10.54381695, 11.50395008,  9.52504414, 13.51878549,
       10.52008813, 10.52763578,  8.51450325, 13.53327691, 17.55058115,
        9.54973496,  8.52642311, 13.50801194, 11.51925127, 17.54056058,
        8.52079463, 11.52952473, 10.52903492, 12.50707959, 11.53554566,
       10.52428446, 11.54627162,  9.52082211, 11.51647984, 15.55987558,
       12.50366294,  9.50681047, 14.51696449, 11.53944801, 20.45070975,
       10.52287032,  8.52989086, 12.52100444, 13.55777678,  9.5100612 ,
        7.47799005,  6.42654662, 13.53582547, 12.51440194,  9.52624688,
        6.43122451, 15.5702764 , 13.51974104, 13.52488542, 11.53189917,
       10.55918696,  9.54426225,  8.52355622, 29.3874453 , 11.50860121,
        8.5257127 ,  7.48142211,  5.49052594, 12.54078016,  4.56595105,
       18.51751052, 11.51931274,  9.50807077,  9.54952803, 14.57780514,
        8.51217819, 13.5127483 , 16.56167508, 12.50610389, 16.55667867,
       12.53122316, 19.4837301 ,  8.49816096, 11.50309575, 10.55417193,
        9.52349301,  6.48881663, 10.5042203 ,  9.56805453, 10.5102838 ,
       13.5842789 , 11.52184874, 11.50674107, 11.52028169,  9.51930599,
       13.55791695,  8.52360608,  8.53312465, 12.51648005, 12.56004323,
       17.54748759,  6.42763084, 10.5714292 , 14.53850484,  9.54040928,
        8.52925688, 10.54163774, 11.58732924,  6.48564358, 13.51670475,
       12.51786108, 10.56413166, 14.5311487 ,  6.42570978,  9.52570151,
       10.54957845, 11.53688629, 12.52276181,  8.5047095 ,  6.42704404,
       11.54858554, 11.54097869,  7.47246051, 12.53781868,  9.50541226,
        9.54783948, 10.50577456, 14.52458737, 11.52825766, 12.50589544,
       11.51067165, 11.51724939,  8.52703679, 16.5706289 , 11.52833183,
        7.45426603, 12.56343543,  8.52706225,  9.51256623, 11.51828459,
       13.53576816, 12.50466016,  8.50151427, 14.53015746, 12.52112141,
       10.50979209,  8.51015893, 13.53824152, 10.5171763 , 10.51975159,
       14.53983965,  9.58030683, 15.56106885,  8.52457131, 15.55307558,
       11.51631637, 10.55513638, 10.55356259, 12.50163651, 11.50487237,
        9.56341769,  9.50870819, 12.50392566,  8.5178435 ,  9.53792433,
        9.5087584 , 14.53564486,  8.52340831, 11.55160183, 13.51786549,
        9.52784638, 11.56950087,  7.46066462,  8.51080824,  6.41681009,
       18.51701837,  9.50502416, 11.53905792,  9.54519979, 10.53785591,
       13.53447042,  9.55485077,  8.4999861 , 10.50944657, 21.39722472,
       10.54947003,  9.52511559,  7.47005775, 10.52393543, 13.51812662,
        9.58006557,  5.40290729, 20.44322268, 14.55279182, 13.53270749,
       10.50772459, 10.51462424, 13.50705682, 13.52582123, 13.56497788,
       10.56824084, 15.5555206 , 13.53484663,  8.52343659, 11.50119043,
       17.54491129, 10.51090888,  9.51983218,  9.52419871,  9.51222307,
       11.53739388,  9.50538223,  9.52373136, 11.54895184,  8.53112367,
        9.54611846, 13.53995072,  7.51401662,  9.50837638,  7.4828657 ,
       11.51835276, 12.55359078,  9.51560324,  7.47739671,  4.4466244 ,
       12.51735684, 11.56954943,  8.51521813, 11.5142779 , 11.50480622,
       15.56484007, 10.52778163, 10.52192177, 12.53815924, 10.52048336,
        7.47435667, 10.54431725, 10.51445428, 10.51310726, 11.52809857,
        9.52423602,  7.46420391, 10.52325616,  8.50695528,  9.56166031,
       15.55203685,  8.52961647,  7.47473101, 18.51843252,  9.51106721,
        7.48594037,  5.40409399,  9.5618124 , 10.51007763, 14.52842531,
        8.52872122,  8.52540269,  4.44607021,  8.52037672,  9.53521496,
       16.57111703, 14.51936971,  6.44542807, 18.5124859 , 10.50913826,
       11.51846919, 14.51982638, 12.55231706, 16.5667273 , 19.47847904,
       22.35216507,  9.51034945, 10.53005147,  7.48908389, 12.50397878,
        8.49687568, 11.51380707, 18.44277692, 15.58089096,  9.56436386,
       17.54286527, 14.5400162 , 10.52211349,  8.54001436,  8.49982272,
       10.51855655, 11.51322957,  8.52168919, 12.57984214,  8.53808005,
        8.51240723, 10.51662303,  7.46564897, 11.57311345, 10.52516972,
        9.55630528,  9.50571303, 18.51887912, 13.54851692, 12.49889877,
       18.52516424, 14.55163454, 10.54191688, 11.56852951, 13.52285267,
       10.50510606,  9.52375898, 10.50652531, 10.52811568, 11.51914211,
       11.50139384, 15.5669624 , 10.56202491, 13.50631401, 14.53624027,
       12.5423551 ,  5.40439196, 10.51676596, 11.51943366, 18.52039105,
        6.48622761, 16.54792748,  9.57850482, 12.50403438,  8.50279315,
       23.39830908, 15.54453062,  9.52985146, 12.58376805, 10.51001899,
       10.51672815,  7.46818687, 12.5406439 , 17.55086448, 10.51906485,
       11.57436581, 15.52727594, 13.55626931,  8.52749663,  8.50031326,
       10.51654562,  7.47164192,  6.42907078,  9.56460715, 13.54644773,
       11.51990548,  5.40157892,  7.46705218,  9.54590865,  8.52138767,
       14.54992062, 11.51941629, 11.54337435,  8.51038422,  9.55858424,
       13.53694559, 15.55706245, 10.53620579, 10.54234576,  9.51286426,
        7.484951  ,  9.5576783 , 12.51796673, 10.5172044 , 19.48264926,
        8.52455323, 11.51400895, 11.50529999, 11.55402501,  7.48516177,
       14.5670974 ,  9.5265175 ,  7.45899483, 15.54324607,  7.48136866,
       13.54403204, 11.55097335, 11.51512549, 12.51461805,  7.46636122,
        9.54122269, 10.51415485,  6.42028644, 14.55531446, 10.52138806,
       16.56029267, 10.52718304,  9.55470898, 10.53583125, 10.54832406,
       10.51532066, 12.51338647, 17.56019888, 10.5900489 , 12.51307539,
       13.51300265, 11.52914925, 17.54482994, 17.54694283,  8.50242255,
       14.53689523,  9.52735438,  9.5525225 , 16.5452941 , 11.52118492,
       10.51612675,  9.52657807, 12.53040187,  6.42028823, 10.52154617,
        9.54642466,  9.54505402, 12.55360079, 10.52605832, 13.54432681,
        9.51860841, 14.54845138, 10.52858872, 11.51959785, 11.50801522,
        8.49477656, 10.55239557,  8.49558516, 10.51297087,  9.5232788 ,
       10.50994826, 11.52006829, 10.56678887, 13.53610753, 11.53948584,
       12.52187189,  9.51379851, 12.51901638, 16.55565733, 12.50343709,
       15.56559024, 12.51944645, 10.51250127,  8.53824049, 13.54084379,
       11.50308885, 10.51832591, 19.5001113 , 11.52252689,  4.44817553,
       10.51394643,  7.48495045,  7.47375331,  8.50077566, 14.55042834,
       13.56452859, 14.54685568, 13.51640251, 11.51864683,  6.42610168,
       12.54981463, 11.50418027, 26.64788122,  8.51107683, 10.52095657,
       11.52251331, 14.52342855, 16.55008177,  6.41510852,  5.40434578,
       11.54912484,  7.46203321, 15.54922553,  7.47410058, 12.5166752 ,
       11.51841231, 10.52503855, 11.50389444, 10.51066803, 10.5333268 ,
       12.56409017, 12.51653992,  8.49097263, 12.54731082, 10.50626534,
       15.53778143,  7.46229106, 14.52534385, 11.56247369, 22.38392041,
       10.52016206, 10.51534495, 11.49916949,  6.42472042, 14.53089851,
       12.50156062, 16.54694765, 11.51492734, 16.55183974, 12.50611422,
       10.50462363,  5.40363215, 10.51301399, 12.51110263, 12.50337116,
       14.57105865])

In [47]:
from sklearn.metrics import r2_score
svr=r2_score(ypr,ytes)
svr

0.9997118252325332

In [44]:
acc_score=[]
c_value=[0.00001,0.001,0.44,0.88,1,20,30]
for i in c_value:
    model_new=SVR(C=i)
    model_new.fit(xtr,ytr)
    ypred=model_new.predict(xtes)
    sc=r2_score(ypred,ytes)
    acc_score.append(sc)

In [41]:
acc_score

[-1150125.0043211414,
 -93.77732344130304,
 0.9868295508910473,
 0.9919525130376227,
 0.9927205828310046,
 0.9996907672072587,
 0.9997118252325332,
 0.999674680022354]

In [42]:
kernel=['linear','rbf','poly','sigmoid']
acc_sc=[]
for i in kernel:
    model_new2=SVR(kernel=i)
    model_new2.fit(xtr,ytr)
    y_pred=model_new2.predict(xtes)
    score=r2_score(ypred,ytes)
    acc_sc.append(score)

In [43]:
report=pd.DataFrame({'Kernel':kernel,'Accuracy':acc_sc})
report

    Kernel  Accuracy
0   linear  0.999675
1      rbf  0.999675
2     poly  0.999675
3  sigmoid  0.999675